#!/bin/bash



source './src/check_sudo.sh'
source './src/development_setup.sh'
source './src/gaming_setup.sh'





function display_menu() {
    echo -e "\n\n------------------------- Modified Ubuntu -------------------------\n"
    echo "1) Development setup"
    echo "2) Gaming setup"
    echo "3) Standard setup"
    echo "0) Exit"
    echo -e "\n\n-------------------------------------------------------------------\n"
}





check_sudo



while true; do
    display_menu

    read -p "Enter the option number: " option

    case $option in
        1) development_setup;;
        2) gaming_setup;;
        0) echo "Exiting..."; exit 0;;
        *) echo "Invalid input. Please try again.";;
    esac
done