#!/bin/bash



source './src/check_sudo'





display_menu() {
    echo -e "\n\n------------------------- Modified Ubuntu -------------------------\n"
    echo "1) Installing Modifications"
    echo "2) See the packages to be installed"
    echo "0) Exit"
    echo -e "\n\n-------------------------------------------------------------------\n"
}





check_sudo



while true; do
    display_menu

    read -p "Enter the option number: " option

    case $option in
        1) echo "Hello World!";;
        2) echo "Hello second World!";;
        0) echo "Exiting..."; exit 0;;
        *) echo "Invalid input. Please try again.";;
    esac
done